### ISSUE TITLE
BasicUCAC.sol should become `interface`?

### ISSUE THREAD

**Issue by aupiff** [blockmason/credit-protocol#22]
Currently, `BasicUCAC.sol` is a simple contract. Once we're closer to having a finalized UCAC / CP architecture, we should create a UCAC interface that all UCACs must inherit from.

**Comment by ghost** [comment]
I agree--how do we enforce this as a constraint?

**Comment by aupiff** [comment]
I don't think it can be enforced. Anything with a function of the signature `function allowTransaction(address creditor, address debtor, uint256 amount) public returns (bool)` will work as a UCAC.

I think you could effectively enforce it by making a UCAC dev tool that makes template UCAC contracts which inherit from `BasicUCAC`. You explain this doesn't add code size, it just guarantees at compile-time that you have a valid UCAC. That should be enough.
