### ISSUE TITLE
Bulk recording & counting of txs when bulk recording

### ISSUE THREAD

**Issue by ghost** [blockmason/credit-protocol#25]
Let's make sure that if bulk recording works, we record N transactions submitted in bulk as N transactions for the purpose of token decay. This adds a lot of value to the network in terms of drastically lowering Eth costs, so we want to capture a small part of that for BCPT.

**Comment by aupiff** [comment]
Good point. I'll definitely do that.

**Comment by aupiff** [comment]
We're going to try a simple for loop over array data as a bulk recording option now.

Figure out the gas cost to record a single CP transaction.

Figure out the gas cost to record N CP transactions via bulk recording.
