### ISSUE TITLE
UCAC Contract Template Ideas

### ISSUE THREAD

**Issue by ghost** [blockmason/credit-protocol#27]
* Mortgage
* Generic interest-bearing loans, with multiple loans per user
* ETH collateralization
* ERC-20 collateral
* Basic P2P (probably extends generic interest bearing)

**Comment by ghost** [comment]
More:
* Payday loans and corresponding documentation and regs (talk more to RG)
* Bankruptcy court and process loans (Ricky)
* Dentist and doctor installment plan payments
* furniture sales installment plan situations

**Comment by ghost** [comment]
* Private investor loans and tracking for real estate (very common in high net worth market, and needs way better tracking)

**Comment by ghost** [comment]
* wager tracking and settlement app

**Comment by DANA-Laboratory** [comment]
While all are good examples of wide usage of CP my question is: (maybe I don't understand CP enougth)
Why there is not a template idea for borrowing something? 
e.g. when a member borrow a book from library, CP could write it, this type of credit will be cleared in two ways
1- if he pays back equal worth of book
2- by bringing back the borrowed item
